### ISSUE TITLE
Open a pop-out widget causes an error when the browser block the pop-up

### ISSUE THREAD

**Issue by Bosio-JeanLouis** [Nciaravola/PonySDK#227]
Here are the browser console logs:
`com.ponysdk.core.terminal.socket.WebSocketClient
SEVERE: Error while processing the Buffer 248 ; position = 564 ; size = 566
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot set property 'onunload' of null`

**Comment by NSV** [comment]
Fix in https://github.com/Nciaravola/PonySDK/commit/6643bce9fb14c488b7463dec0bebfd2c86448bbe
