### ISSUE TITLE
Error when transient dates array is > 255

### ISSUE THREAD

**Issue by st-jbreliaud** [Nciaravola/PonySDK#253]
There's an error when setting a list of dates with a size > 255 in the method PDatePicker.setTransientEnabledOnDates(boolean enabled, Collection<Date> dates).

> 15:51:47.823 ERROR qtp379207821-226 [UIContext] Cannot process client instruction15:51:47.823 ERROR qtp379207821-226 [UIContext] Cannot process client instructionjava.lang.IllegalArgumentException: Array is too big (492 > 255), use a Json Object instead : [1519599600000, 1519686000000, 1519772400000, 1519858800000, 1519945200000, 1520031600000, 152011800... at com.ponysdk.core.server.websocket.WebSocketPusher.write(WebSocketPusher.java:205) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.server.websocket.WebSocketPusher.encode(WebSocketPusher.java:144) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.server.websocket.WebSocket.encode(WebSocket.java:285) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.writer.ModelWriter.write(ModelWriter.java:59) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.ui.basic.PDatePicker.lambda$setTransientEnabledOnDates$0(PDatePicker.java:181) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.ui.basic.PObject.writeUpdate(PObject.java:244) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.ui.basic.PObject.saveUpdate(PObject.java:232) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.ui.basic.PObject.saveUpdate(PObject.java:222) ~[ponysdk-2.8.14.jar:2.8.14] at com.ponysdk.core.ui.basic.PDatePicker.setTransientEnabledOnDates(PDatePicker.java:180) ~[ponysdk-2.8.14.jar:2.8.14]

The list is converted in an array before being sent to the client.
It must be cut in sublists with a size < 255 to avoid exception.

**Comment by aminebag** [comment]
Fixed in : https://github.com/Nciaravola/PonySDK/commit/b1995553ecdd9e8d7a4c16a444fd9fdb9c07b270
